//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更此檔案可能會導致不正確的行為，而且若已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseReqInParm", Namespace="http://schemas.datacontract.org/2004/07/Shared")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ExchangeService.CGenOneReqInParmOfIntfLogZTgN8_PBM))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ExchangeService.CCertificateReqInParm))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ExchangeService.CCertificateSpcReqInParm))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ExchangeService.CInstitutionReqInParm))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ExchangeService.CInstitutionDistReqInParm))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ExchangeService.CPersonnelReqInParm))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ExchangeService.CPracticeReqInParm))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ExchangeService.CGenOneStringReqInParm))]
    public partial class BaseReqInParm : object
    {
        
        private ExchangeService.ReqCode ReqCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExchangeService.ReqCode ReqCode
        {
            get
            {
                return this.ReqCodeField;
            }
            set
            {
                this.ReqCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReqCode", Namespace="http://schemas.datacontract.org/2004/07/Shared")]
    public partial class ReqCode : object
    {
        
        private string AppNameField;
        
        private string AppVersionField;
        
        private string FunNameField;
        
        private System.Nullable<int> PreSeqField;
        
        private int SeqField;
        
        private string UserIDField;
        
        private string UserPwdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppName
        {
            get
            {
                return this.AppNameField;
            }
            set
            {
                this.AppNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppVersion
        {
            get
            {
                return this.AppVersionField;
            }
            set
            {
                this.AppVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FunName
        {
            get
            {
                return this.FunNameField;
            }
            set
            {
                this.FunNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PreSeq
        {
            get
            {
                return this.PreSeqField;
            }
            set
            {
                this.PreSeqField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Seq
        {
            get
            {
                return this.SeqField;
            }
            set
            {
                this.SeqField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPwd
        {
            get
            {
                return this.UserPwdField;
            }
            set
            {
                this.UserPwdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CGenOneReqInParmOfIntfLogZTgN8_PBM", Namespace="http://schemas.datacontract.org/2004/07/DTO.ReqInParm")]
    public partial class CGenOneReqInParmOfIntfLogZTgN8_PBM : ExchangeService.BaseReqInParm
    {
        
        private ExchangeService.IntfLog Parm_01Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExchangeService.IntfLog Parm_01
        {
            get
            {
                return this.Parm_01Field;
            }
            set
            {
                this.Parm_01Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CCertificateReqInParm", Namespace="http://schemas.datacontract.org/2004/07/DTO.ReqInParm")]
    public partial class CCertificateReqInParm : ExchangeService.BaseReqInParm
    {
        
        private ExchangeService.ActionType ActionTypeField;
        
        private ExchangeService.Certificate[] CertificatesField;
        
        private string IgnoreFieldsField;
        
        private string UpdateFieldsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExchangeService.ActionType ActionType
        {
            get
            {
                return this.ActionTypeField;
            }
            set
            {
                this.ActionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExchangeService.Certificate[] Certificates
        {
            get
            {
                return this.CertificatesField;
            }
            set
            {
                this.CertificatesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IgnoreFields
        {
            get
            {
                return this.IgnoreFieldsField;
            }
            set
            {
                this.IgnoreFieldsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateFields
        {
            get
            {
                return this.UpdateFieldsField;
            }
            set
            {
                this.UpdateFieldsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CCertificateSpcReqInParm", Namespace="http://schemas.datacontract.org/2004/07/DTO.ReqInParm")]
    public partial class CCertificateSpcReqInParm : ExchangeService.BaseReqInParm
    {
        
        private ExchangeService.ActionType ActionTypeField;
        
        private ExchangeService.CertificateSpc[] CertificateSpcsField;
        
        private string IgnoreFieldsField;
        
        private string UpdateFieldsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExchangeService.ActionType ActionType
        {
            get
            {
                return this.ActionTypeField;
            }
            set
            {
                this.ActionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExchangeService.CertificateSpc[] CertificateSpcs
        {
            get
            {
                return this.CertificateSpcsField;
            }
            set
            {
                this.CertificateSpcsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IgnoreFields
        {
            get
            {
                return this.IgnoreFieldsField;
            }
            set
            {
                this.IgnoreFieldsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateFields
        {
            get
            {
                return this.UpdateFieldsField;
            }
            set
            {
                this.UpdateFieldsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CInstitutionReqInParm", Namespace="http://schemas.datacontract.org/2004/07/DTO.ReqInParm")]
    public partial class CInstitutionReqInParm : ExchangeService.BaseReqInParm
    {
        
        private ExchangeService.ActionType ActionTypeField;
        
        private string IgnoreFieldsField;
        
        private ExchangeService.Institution[] InstitutionsField;
        
        private string UpdateFieldsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExchangeService.ActionType ActionType
        {
            get
            {
                return this.ActionTypeField;
            }
            set
            {
                this.ActionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IgnoreFields
        {
            get
            {
                return this.IgnoreFieldsField;
            }
            set
            {
                this.IgnoreFieldsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExchangeService.Institution[] Institutions
        {
            get
            {
                return this.InstitutionsField;
            }
            set
            {
                this.InstitutionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateFields
        {
            get
            {
                return this.UpdateFieldsField;
            }
            set
            {
                this.UpdateFieldsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CInstitutionDistReqInParm", Namespace="http://schemas.datacontract.org/2004/07/DTO.ReqInParm")]
    public partial class CInstitutionDistReqInParm : ExchangeService.BaseReqInParm
    {
        
        private ExchangeService.ActionType ActionTypeField;
        
        private string IgnoreFieldsField;
        
        private ExchangeService.InstitutionDist[] InstitutionDistsField;
        
        private string UpdateFieldsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExchangeService.ActionType ActionType
        {
            get
            {
                return this.ActionTypeField;
            }
            set
            {
                this.ActionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IgnoreFields
        {
            get
            {
                return this.IgnoreFieldsField;
            }
            set
            {
                this.IgnoreFieldsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExchangeService.InstitutionDist[] InstitutionDists
        {
            get
            {
                return this.InstitutionDistsField;
            }
            set
            {
                this.InstitutionDistsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateFields
        {
            get
            {
                return this.UpdateFieldsField;
            }
            set
            {
                this.UpdateFieldsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CPersonnelReqInParm", Namespace="http://schemas.datacontract.org/2004/07/DTO.ReqInParm")]
    public partial class CPersonnelReqInParm : ExchangeService.BaseReqInParm
    {
        
        private ExchangeService.ActionType ActionTypeField;
        
        private string IgnoreFieldsField;
        
        private ExchangeService.Personnel[] PersonnelsField;
        
        private string UpdateFieldsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExchangeService.ActionType ActionType
        {
            get
            {
                return this.ActionTypeField;
            }
            set
            {
                this.ActionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IgnoreFields
        {
            get
            {
                return this.IgnoreFieldsField;
            }
            set
            {
                this.IgnoreFieldsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExchangeService.Personnel[] Personnels
        {
            get
            {
                return this.PersonnelsField;
            }
            set
            {
                this.PersonnelsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateFields
        {
            get
            {
                return this.UpdateFieldsField;
            }
            set
            {
                this.UpdateFieldsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CPracticeReqInParm", Namespace="http://schemas.datacontract.org/2004/07/DTO.ReqInParm")]
    public partial class CPracticeReqInParm : ExchangeService.BaseReqInParm
    {
        
        private ExchangeService.ActionType ActionTypeField;
        
        private string IgnoreFieldsField;
        
        private ExchangeService.Practice[] PracticesField;
        
        private string UpdateFieldsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExchangeService.ActionType ActionType
        {
            get
            {
                return this.ActionTypeField;
            }
            set
            {
                this.ActionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IgnoreFields
        {
            get
            {
                return this.IgnoreFieldsField;
            }
            set
            {
                this.IgnoreFieldsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExchangeService.Practice[] Practices
        {
            get
            {
                return this.PracticesField;
            }
            set
            {
                this.PracticesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateFields
        {
            get
            {
                return this.UpdateFieldsField;
            }
            set
            {
                this.UpdateFieldsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CGenOneStringReqInParm", Namespace="http://schemas.datacontract.org/2004/07/DTO.ReqInParm")]
    public partial class CGenOneStringReqInParm : ExchangeService.BaseReqInParm
    {
        
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntfLog", Namespace="http://schemas.datacontract.org/2004/07/DTO.DB")]
    public partial class IntfLog : object
    {
        
        private System.DateTime Log_InftDateField;
        
        private string Log_MessageField;
        
        private decimal Log_ProcessTimeField;
        
        private int Log_RecFaileField;
        
        private int Log_RecSuccessField;
        
        private long Log_SeqField;
        
        private string Log_SourceFileField;
        
        private int Pfm_IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Log_InftDate
        {
            get
            {
                return this.Log_InftDateField;
            }
            set
            {
                this.Log_InftDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Log_Message
        {
            get
            {
                return this.Log_MessageField;
            }
            set
            {
                this.Log_MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Log_ProcessTime
        {
            get
            {
                return this.Log_ProcessTimeField;
            }
            set
            {
                this.Log_ProcessTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Log_RecFaile
        {
            get
            {
                return this.Log_RecFaileField;
            }
            set
            {
                this.Log_RecFaileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Log_RecSuccess
        {
            get
            {
                return this.Log_RecSuccessField;
            }
            set
            {
                this.Log_RecSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Log_Seq
        {
            get
            {
                return this.Log_SeqField;
            }
            set
            {
                this.Log_SeqField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Log_SourceFile
        {
            get
            {
                return this.Log_SourceFileField;
            }
            set
            {
                this.Log_SourceFileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pfm_Id
        {
            get
            {
                return this.Pfm_IdField;
            }
            set
            {
                this.Pfm_IdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActionType", Namespace="http://schemas.datacontract.org/2004/07/DTO.Enum")]
    public enum ActionType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modify = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Add = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Certificate", Namespace="http://schemas.datacontract.org/2004/07/DTO.DB.MA")]
    public partial class Certificate : object
    {
        
        private string CER_DOC_IDField;
        
        private string CER_DOC_NOField;
        
        private string CER_FLAGField;
        
        private string CER_REF_IDField;
        
        private string CET_APPLY_MField;
        
        private System.Nullable<System.DateTime> CET_APPROVE_DATEField;
        
        private string CET_APPROVE_IDField;
        
        private string CET_APPROVE_NOField;
        
        private System.Nullable<System.DateTime> CET_ISSUE_DATEField;
        
        private string CET_REASON_MField;
        
        private string DOC_ID_NOField;
        
        private System.DateTime Intf_DateField;
        
        private string MASTER_FLAGField;
        
        private string REF_NAMEField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CER_DOC_ID
        {
            get
            {
                return this.CER_DOC_IDField;
            }
            set
            {
                this.CER_DOC_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CER_DOC_NO
        {
            get
            {
                return this.CER_DOC_NOField;
            }
            set
            {
                this.CER_DOC_NOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CER_FLAG
        {
            get
            {
                return this.CER_FLAGField;
            }
            set
            {
                this.CER_FLAGField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CER_REF_ID
        {
            get
            {
                return this.CER_REF_IDField;
            }
            set
            {
                this.CER_REF_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CET_APPLY_M
        {
            get
            {
                return this.CET_APPLY_MField;
            }
            set
            {
                this.CET_APPLY_MField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CET_APPROVE_DATE
        {
            get
            {
                return this.CET_APPROVE_DATEField;
            }
            set
            {
                this.CET_APPROVE_DATEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CET_APPROVE_ID
        {
            get
            {
                return this.CET_APPROVE_IDField;
            }
            set
            {
                this.CET_APPROVE_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CET_APPROVE_NO
        {
            get
            {
                return this.CET_APPROVE_NOField;
            }
            set
            {
                this.CET_APPROVE_NOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CET_ISSUE_DATE
        {
            get
            {
                return this.CET_ISSUE_DATEField;
            }
            set
            {
                this.CET_ISSUE_DATEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CET_REASON_M
        {
            get
            {
                return this.CET_REASON_MField;
            }
            set
            {
                this.CET_REASON_MField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOC_ID_NO
        {
            get
            {
                return this.DOC_ID_NOField;
            }
            set
            {
                this.DOC_ID_NOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Intf_Date
        {
            get
            {
                return this.Intf_DateField;
            }
            set
            {
                this.Intf_DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MASTER_FLAG
        {
            get
            {
                return this.MASTER_FLAGField;
            }
            set
            {
                this.MASTER_FLAGField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REF_NAME
        {
            get
            {
                return this.REF_NAMEField;
            }
            set
            {
                this.REF_NAMEField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CertificateSpc", Namespace="http://schemas.datacontract.org/2004/07/DTO.DB.MA")]
    public partial class CertificateSpc : object
    {
        
        private string DOC_ID_NOField;
        
        private System.DateTime Intf_DateField;
        
        private string SDW_DEPT_NAMEField;
        
        private string SDW_NAMEField;
        
        private string SPC_FLAGField;
        
        private System.Nullable<System.DateTime> SPC_ISSUE_DATEField;
        
        private System.Nullable<System.DateTime> SPC_LIC_BDATEField;
        
        private System.Nullable<System.DateTime> SPC_LIC_EDATEField;
        
        private string SPC_SDW_IDField;
        
        private string SPC_SDW_NOField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOC_ID_NO
        {
            get
            {
                return this.DOC_ID_NOField;
            }
            set
            {
                this.DOC_ID_NOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Intf_Date
        {
            get
            {
                return this.Intf_DateField;
            }
            set
            {
                this.Intf_DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SDW_DEPT_NAME
        {
            get
            {
                return this.SDW_DEPT_NAMEField;
            }
            set
            {
                this.SDW_DEPT_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SDW_NAME
        {
            get
            {
                return this.SDW_NAMEField;
            }
            set
            {
                this.SDW_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SPC_FLAG
        {
            get
            {
                return this.SPC_FLAGField;
            }
            set
            {
                this.SPC_FLAGField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SPC_ISSUE_DATE
        {
            get
            {
                return this.SPC_ISSUE_DATEField;
            }
            set
            {
                this.SPC_ISSUE_DATEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SPC_LIC_BDATE
        {
            get
            {
                return this.SPC_LIC_BDATEField;
            }
            set
            {
                this.SPC_LIC_BDATEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SPC_LIC_EDATE
        {
            get
            {
                return this.SPC_LIC_EDATEField;
            }
            set
            {
                this.SPC_LIC_EDATEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SPC_SDW_ID
        {
            get
            {
                return this.SPC_SDW_IDField;
            }
            set
            {
                this.SPC_SDW_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SPC_SDW_NO
        {
            get
            {
                return this.SPC_SDW_NOField;
            }
            set
            {
                this.SPC_SDW_NOField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Institution", Namespace="http://schemas.datacontract.org/2004/07/DTO.DB.MA")]
    public partial class Institution : object
    {
        
        private string AREA_NAMEField;
        
        private string AUTHOR_IDField;
        
        private string AUTHOR_NAMEField;
        
        private string BAS_ADDRField;
        
        private string BAS_AGENCY_IDField;
        
        private string BAS_ALIASField;
        
        private System.Nullable<System.DateTime> BAS_APP_DATEField;
        
        private string BAS_APP_IDField;
        
        private string BAS_APP_NOField;
        
        private System.Nullable<System.DateTime> BAS_HAD_BIRTHField;
        
        private string BAS_HAD_CER_IDField;
        
        private string BAS_HAD_CER_NAMEField;
        
        private string BAS_HAD_CER_NOField;
        
        private string BAS_HAD_ID_NOField;
        
        private string BAS_HAD_NAMEField;
        
        private string BAS_HAD_SEXField;
        
        private System.Nullable<System.DateTime> BAS_LIC_DATEField;
        
        private string BAS_LIC_IDField;
        
        private string BAS_LIC_NOField;
        
        private string BAS_NAMEField;
        
        private string BAS_STATUSField;
        
        private string BAS_STATUS_NAMEField;
        
        private string BAS_TEL_NOField;
        
        private System.DateTime Intf_DateField;
        
        private string MULASE_FLAGField;
        
        private string TYPE_IDField;
        
        private string TYPE_NAMEField;
        
        private string ZIP_NAMEField;
        
        private string ZONE_AREA_CODEField;
        
        private string ZONE_ZIP_CODEField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AREA_NAME
        {
            get
            {
                return this.AREA_NAMEField;
            }
            set
            {
                this.AREA_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AUTHOR_ID
        {
            get
            {
                return this.AUTHOR_IDField;
            }
            set
            {
                this.AUTHOR_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AUTHOR_NAME
        {
            get
            {
                return this.AUTHOR_NAMEField;
            }
            set
            {
                this.AUTHOR_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BAS_ADDR
        {
            get
            {
                return this.BAS_ADDRField;
            }
            set
            {
                this.BAS_ADDRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BAS_AGENCY_ID
        {
            get
            {
                return this.BAS_AGENCY_IDField;
            }
            set
            {
                this.BAS_AGENCY_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BAS_ALIAS
        {
            get
            {
                return this.BAS_ALIASField;
            }
            set
            {
                this.BAS_ALIASField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BAS_APP_DATE
        {
            get
            {
                return this.BAS_APP_DATEField;
            }
            set
            {
                this.BAS_APP_DATEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BAS_APP_ID
        {
            get
            {
                return this.BAS_APP_IDField;
            }
            set
            {
                this.BAS_APP_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BAS_APP_NO
        {
            get
            {
                return this.BAS_APP_NOField;
            }
            set
            {
                this.BAS_APP_NOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BAS_HAD_BIRTH
        {
            get
            {
                return this.BAS_HAD_BIRTHField;
            }
            set
            {
                this.BAS_HAD_BIRTHField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BAS_HAD_CER_ID
        {
            get
            {
                return this.BAS_HAD_CER_IDField;
            }
            set
            {
                this.BAS_HAD_CER_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BAS_HAD_CER_NAME
        {
            get
            {
                return this.BAS_HAD_CER_NAMEField;
            }
            set
            {
                this.BAS_HAD_CER_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BAS_HAD_CER_NO
        {
            get
            {
                return this.BAS_HAD_CER_NOField;
            }
            set
            {
                this.BAS_HAD_CER_NOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BAS_HAD_ID_NO
        {
            get
            {
                return this.BAS_HAD_ID_NOField;
            }
            set
            {
                this.BAS_HAD_ID_NOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BAS_HAD_NAME
        {
            get
            {
                return this.BAS_HAD_NAMEField;
            }
            set
            {
                this.BAS_HAD_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BAS_HAD_SEX
        {
            get
            {
                return this.BAS_HAD_SEXField;
            }
            set
            {
                this.BAS_HAD_SEXField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BAS_LIC_DATE
        {
            get
            {
                return this.BAS_LIC_DATEField;
            }
            set
            {
                this.BAS_LIC_DATEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BAS_LIC_ID
        {
            get
            {
                return this.BAS_LIC_IDField;
            }
            set
            {
                this.BAS_LIC_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BAS_LIC_NO
        {
            get
            {
                return this.BAS_LIC_NOField;
            }
            set
            {
                this.BAS_LIC_NOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BAS_NAME
        {
            get
            {
                return this.BAS_NAMEField;
            }
            set
            {
                this.BAS_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BAS_STATUS
        {
            get
            {
                return this.BAS_STATUSField;
            }
            set
            {
                this.BAS_STATUSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BAS_STATUS_NAME
        {
            get
            {
                return this.BAS_STATUS_NAMEField;
            }
            set
            {
                this.BAS_STATUS_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BAS_TEL_NO
        {
            get
            {
                return this.BAS_TEL_NOField;
            }
            set
            {
                this.BAS_TEL_NOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Intf_Date
        {
            get
            {
                return this.Intf_DateField;
            }
            set
            {
                this.Intf_DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MULASE_FLAG
        {
            get
            {
                return this.MULASE_FLAGField;
            }
            set
            {
                this.MULASE_FLAGField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TYPE_ID
        {
            get
            {
                return this.TYPE_IDField;
            }
            set
            {
                this.TYPE_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TYPE_NAME
        {
            get
            {
                return this.TYPE_NAMEField;
            }
            set
            {
                this.TYPE_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZIP_NAME
        {
            get
            {
                return this.ZIP_NAMEField;
            }
            set
            {
                this.ZIP_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZONE_AREA_CODE
        {
            get
            {
                return this.ZONE_AREA_CODEField;
            }
            set
            {
                this.ZONE_AREA_CODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZONE_ZIP_CODE
        {
            get
            {
                return this.ZONE_ZIP_CODEField;
            }
            set
            {
                this.ZONE_ZIP_CODEField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InstitutionDist", Namespace="http://schemas.datacontract.org/2004/07/DTO.DB.MA")]
    public partial class InstitutionDist : object
    {
        
        private string AREA_NAMEField;
        
        private string BAS_ADDRField;
        
        private string BAS_AGENCY_IDField;
        
        private System.DateTime Intf_DateField;
        
        private string ZIP_NAMEField;
        
        private string ZONE_AREA_CODEField;
        
        private string ZONE_CODEField;
        
        private string ZONE_MAINField;
        
        private string ZONE_NAMEField;
        
        private string ZONE_ZIP_CODEField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AREA_NAME
        {
            get
            {
                return this.AREA_NAMEField;
            }
            set
            {
                this.AREA_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BAS_ADDR
        {
            get
            {
                return this.BAS_ADDRField;
            }
            set
            {
                this.BAS_ADDRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BAS_AGENCY_ID
        {
            get
            {
                return this.BAS_AGENCY_IDField;
            }
            set
            {
                this.BAS_AGENCY_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Intf_Date
        {
            get
            {
                return this.Intf_DateField;
            }
            set
            {
                this.Intf_DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZIP_NAME
        {
            get
            {
                return this.ZIP_NAMEField;
            }
            set
            {
                this.ZIP_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZONE_AREA_CODE
        {
            get
            {
                return this.ZONE_AREA_CODEField;
            }
            set
            {
                this.ZONE_AREA_CODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZONE_CODE
        {
            get
            {
                return this.ZONE_CODEField;
            }
            set
            {
                this.ZONE_CODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZONE_MAIN
        {
            get
            {
                return this.ZONE_MAINField;
            }
            set
            {
                this.ZONE_MAINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZONE_NAME
        {
            get
            {
                return this.ZONE_NAMEField;
            }
            set
            {
                this.ZONE_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZONE_ZIP_CODE
        {
            get
            {
                return this.ZONE_ZIP_CODEField;
            }
            set
            {
                this.ZONE_ZIP_CODEField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Personnel", Namespace="http://schemas.datacontract.org/2004/07/DTO.DB.MA")]
    public partial class Personnel : object
    {
        
        private string DOC_ADDR1Field;
        
        private string DOC_ADDR2Field;
        
        private System.Nullable<System.DateTime> DOC_BIRTHField;
        
        private string DOC_ENGLISH_NAMEField;
        
        private string DOC_ID_NOField;
        
        private string DOC_NAMEField;
        
        private string DOC_SEXField;
        
        private string DOC_TEL_NOField;
        
        private System.DateTime Intf_DateField;
        
        private string MPRSIZ_FLAGField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOC_ADDR1
        {
            get
            {
                return this.DOC_ADDR1Field;
            }
            set
            {
                this.DOC_ADDR1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOC_ADDR2
        {
            get
            {
                return this.DOC_ADDR2Field;
            }
            set
            {
                this.DOC_ADDR2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DOC_BIRTH
        {
            get
            {
                return this.DOC_BIRTHField;
            }
            set
            {
                this.DOC_BIRTHField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOC_ENGLISH_NAME
        {
            get
            {
                return this.DOC_ENGLISH_NAMEField;
            }
            set
            {
                this.DOC_ENGLISH_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOC_ID_NO
        {
            get
            {
                return this.DOC_ID_NOField;
            }
            set
            {
                this.DOC_ID_NOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOC_NAME
        {
            get
            {
                return this.DOC_NAMEField;
            }
            set
            {
                this.DOC_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOC_SEX
        {
            get
            {
                return this.DOC_SEXField;
            }
            set
            {
                this.DOC_SEXField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOC_TEL_NO
        {
            get
            {
                return this.DOC_TEL_NOField;
            }
            set
            {
                this.DOC_TEL_NOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Intf_Date
        {
            get
            {
                return this.Intf_DateField;
            }
            set
            {
                this.Intf_DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MPRSIZ_FLAG
        {
            get
            {
                return this.MPRSIZ_FLAGField;
            }
            set
            {
                this.MPRSIZ_FLAGField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Practice", Namespace="http://schemas.datacontract.org/2004/07/DTO.DB.MA")]
    public partial class Practice : object
    {
        
        private string BAS_AGENCY_IDField;
        
        private string BAS_NAMEField;
        
        private string CER_DOC_IDField;
        
        private string CER_DOC_NOField;
        
        private string CER_REF_IDField;
        
        private string DOC_ID_NOField;
        
        private System.DateTime Intf_DateField;
        
        private string PRO_STATUS_MField;
        
        private string PRO_STATUS_M_NAMEField;
        
        private System.Nullable<System.DateTime> PRT_APPLY_DATEField;
        
        private string PRT_AREAField;
        
        private string PRT_AREA_NAMEField;
        
        private string PRT_DEPT_1Field;
        
        private string PRT_DEPT_2Field;
        
        private string PRT_DEPT_3Field;
        
        private string PRT_DEPT_4Field;
        
        private string PRT_DEPT_5Field;
        
        private string PRT_DEPT_ID_1Field;
        
        private string PRT_DEPT_ID_2Field;
        
        private string PRT_DEPT_ID_3Field;
        
        private string PRT_DEPT_ID_4Field;
        
        private string PRT_DEPT_ID_5Field;
        
        private System.Nullable<System.DateTime> PRT_LIC_BDATEField;
        
        private System.Nullable<System.DateTime> PRT_LIC_EDATEField;
        
        private string PRT_LIC_IDField;
        
        private string PRT_LIC_NOField;
        
        private string REF_NAMEField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BAS_AGENCY_ID
        {
            get
            {
                return this.BAS_AGENCY_IDField;
            }
            set
            {
                this.BAS_AGENCY_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BAS_NAME
        {
            get
            {
                return this.BAS_NAMEField;
            }
            set
            {
                this.BAS_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CER_DOC_ID
        {
            get
            {
                return this.CER_DOC_IDField;
            }
            set
            {
                this.CER_DOC_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CER_DOC_NO
        {
            get
            {
                return this.CER_DOC_NOField;
            }
            set
            {
                this.CER_DOC_NOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CER_REF_ID
        {
            get
            {
                return this.CER_REF_IDField;
            }
            set
            {
                this.CER_REF_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOC_ID_NO
        {
            get
            {
                return this.DOC_ID_NOField;
            }
            set
            {
                this.DOC_ID_NOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Intf_Date
        {
            get
            {
                return this.Intf_DateField;
            }
            set
            {
                this.Intf_DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRO_STATUS_M
        {
            get
            {
                return this.PRO_STATUS_MField;
            }
            set
            {
                this.PRO_STATUS_MField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRO_STATUS_M_NAME
        {
            get
            {
                return this.PRO_STATUS_M_NAMEField;
            }
            set
            {
                this.PRO_STATUS_M_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PRT_APPLY_DATE
        {
            get
            {
                return this.PRT_APPLY_DATEField;
            }
            set
            {
                this.PRT_APPLY_DATEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRT_AREA
        {
            get
            {
                return this.PRT_AREAField;
            }
            set
            {
                this.PRT_AREAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRT_AREA_NAME
        {
            get
            {
                return this.PRT_AREA_NAMEField;
            }
            set
            {
                this.PRT_AREA_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRT_DEPT_1
        {
            get
            {
                return this.PRT_DEPT_1Field;
            }
            set
            {
                this.PRT_DEPT_1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRT_DEPT_2
        {
            get
            {
                return this.PRT_DEPT_2Field;
            }
            set
            {
                this.PRT_DEPT_2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRT_DEPT_3
        {
            get
            {
                return this.PRT_DEPT_3Field;
            }
            set
            {
                this.PRT_DEPT_3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRT_DEPT_4
        {
            get
            {
                return this.PRT_DEPT_4Field;
            }
            set
            {
                this.PRT_DEPT_4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRT_DEPT_5
        {
            get
            {
                return this.PRT_DEPT_5Field;
            }
            set
            {
                this.PRT_DEPT_5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRT_DEPT_ID_1
        {
            get
            {
                return this.PRT_DEPT_ID_1Field;
            }
            set
            {
                this.PRT_DEPT_ID_1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRT_DEPT_ID_2
        {
            get
            {
                return this.PRT_DEPT_ID_2Field;
            }
            set
            {
                this.PRT_DEPT_ID_2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRT_DEPT_ID_3
        {
            get
            {
                return this.PRT_DEPT_ID_3Field;
            }
            set
            {
                this.PRT_DEPT_ID_3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRT_DEPT_ID_4
        {
            get
            {
                return this.PRT_DEPT_ID_4Field;
            }
            set
            {
                this.PRT_DEPT_ID_4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRT_DEPT_ID_5
        {
            get
            {
                return this.PRT_DEPT_ID_5Field;
            }
            set
            {
                this.PRT_DEPT_ID_5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PRT_LIC_BDATE
        {
            get
            {
                return this.PRT_LIC_BDATEField;
            }
            set
            {
                this.PRT_LIC_BDATEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PRT_LIC_EDATE
        {
            get
            {
                return this.PRT_LIC_EDATEField;
            }
            set
            {
                this.PRT_LIC_EDATEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRT_LIC_ID
        {
            get
            {
                return this.PRT_LIC_IDField;
            }
            set
            {
                this.PRT_LIC_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRT_LIC_NO
        {
            get
            {
                return this.PRT_LIC_NOField;
            }
            set
            {
                this.PRT_LIC_NOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REF_NAME
        {
            get
            {
                return this.REF_NAMEField;
            }
            set
            {
                this.REF_NAMEField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseReqResult", Namespace="http://schemas.datacontract.org/2004/07/Shared")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ExchangeService.CGenOneReqResultOfdecimal))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ExchangeService.CGenOneReqResultOfint))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ExchangeService.CGenOneReqResultOfIntfPlatformZTgN8_PBM))]
    public partial class BaseReqResult : object
    {
        
        private ExchangeService.RetCode RetCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExchangeService.RetCode RetCode
        {
            get
            {
                return this.RetCodeField;
            }
            set
            {
                this.RetCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetCode", Namespace="http://schemas.datacontract.org/2004/07/Shared")]
    public partial class RetCode : object
    {
        
        private string EnvironmentField;
        
        private System.Nullable<int> FunIdField;
        
        private string FunNameField;
        
        private string MessageTextField;
        
        private ExchangeService.Message[] MsgSequenceField;
        
        private System.Nullable<int> PreSeqField;
        
        private string ReturnCodeField;
        
        private int SeqField;
        
        private int TableTotalRowField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Environment
        {
            get
            {
                return this.EnvironmentField;
            }
            set
            {
                this.EnvironmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FunId
        {
            get
            {
                return this.FunIdField;
            }
            set
            {
                this.FunIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FunName
        {
            get
            {
                return this.FunNameField;
            }
            set
            {
                this.FunNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageText
        {
            get
            {
                return this.MessageTextField;
            }
            set
            {
                this.MessageTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExchangeService.Message[] MsgSequence
        {
            get
            {
                return this.MsgSequenceField;
            }
            set
            {
                this.MsgSequenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PreSeq
        {
            get
            {
                return this.PreSeqField;
            }
            set
            {
                this.PreSeqField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnCode
        {
            get
            {
                return this.ReturnCodeField;
            }
            set
            {
                this.ReturnCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Seq
        {
            get
            {
                return this.SeqField;
            }
            set
            {
                this.SeqField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TableTotalRow
        {
            get
            {
                return this.TableTotalRowField;
            }
            set
            {
                this.TableTotalRowField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CGenOneReqResultOfdecimal", Namespace="http://schemas.datacontract.org/2004/07/DTO.ReqResult")]
    public partial class CGenOneReqResultOfdecimal : ExchangeService.BaseReqResult
    {
        
        private decimal Result_01Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Result_01
        {
            get
            {
                return this.Result_01Field;
            }
            set
            {
                this.Result_01Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CGenOneReqResultOfint", Namespace="http://schemas.datacontract.org/2004/07/DTO.ReqResult")]
    public partial class CGenOneReqResultOfint : ExchangeService.BaseReqResult
    {
        
        private int Result_01Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Result_01
        {
            get
            {
                return this.Result_01Field;
            }
            set
            {
                this.Result_01Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CGenOneReqResultOfIntfPlatformZTgN8_PBM", Namespace="http://schemas.datacontract.org/2004/07/DTO.ReqResult")]
    public partial class CGenOneReqResultOfIntfPlatformZTgN8_PBM : ExchangeService.BaseReqResult
    {
        
        private ExchangeService.IntfPlatform Result_01Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExchangeService.IntfPlatform Result_01
        {
            get
            {
                return this.Result_01Field;
            }
            set
            {
                this.Result_01Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntfPlatform", Namespace="http://schemas.datacontract.org/2004/07/DTO.DB")]
    public partial class IntfPlatform : object
    {
        
        private System.DateTime CR_DateField;
        
        private string Pfm_CodeField;
        
        private bool Pfm_DownLoadField;
        
        private int Pfm_IdField;
        
        private bool Pfm_IsUploadField;
        
        private string Pfm_NameField;
        
        private string Pfm_ProtocalField;
        
        private string Pfm_ServiceLocField;
        
        private System.DateTime UD_DateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CR_Date
        {
            get
            {
                return this.CR_DateField;
            }
            set
            {
                this.CR_DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pfm_Code
        {
            get
            {
                return this.Pfm_CodeField;
            }
            set
            {
                this.Pfm_CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Pfm_DownLoad
        {
            get
            {
                return this.Pfm_DownLoadField;
            }
            set
            {
                this.Pfm_DownLoadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pfm_Id
        {
            get
            {
                return this.Pfm_IdField;
            }
            set
            {
                this.Pfm_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Pfm_IsUpload
        {
            get
            {
                return this.Pfm_IsUploadField;
            }
            set
            {
                this.Pfm_IsUploadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pfm_Name
        {
            get
            {
                return this.Pfm_NameField;
            }
            set
            {
                this.Pfm_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pfm_Protocal
        {
            get
            {
                return this.Pfm_ProtocalField;
            }
            set
            {
                this.Pfm_ProtocalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pfm_ServiceLoc
        {
            get
            {
                return this.Pfm_ServiceLocField;
            }
            set
            {
                this.Pfm_ServiceLocField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UD_Date
        {
            get
            {
                return this.UD_DateField;
            }
            set
            {
                this.UD_DateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/Shared")]
    public partial class Message : object
    {
        
        private System.DateTime CreateDateField;
        
        private string MessageTextField;
        
        private ExchangeService.MsgType TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate
        {
            get
            {
                return this.CreateDateField;
            }
            set
            {
                this.CreateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageText
        {
            get
            {
                return this.MessageTextField;
            }
            set
            {
                this.MessageTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExchangeService.MsgType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgType", Namespace="http://schemas.datacontract.org/2004/07/Shared")]
    public enum MsgType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DEBUG = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INFO = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WARN = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FATAL = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MSGCODE = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExchangeService.IMainService")]
    public interface IMainService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/GetPlatformInfo", ReplyAction="http://tempuri.org/IGeneralService/GetPlatformInfoResponse")]
        System.Threading.Tasks.Task<ExchangeService.CGenOneReqResultOfIntfPlatformZTgN8_PBM> GetPlatformInfoAsync(ExchangeService.CGenOneStringReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/WriteInterfaceLog", ReplyAction="http://tempuri.org/IGeneralService/WriteInterfaceLogResponse")]
        System.Threading.Tasks.Task<ExchangeService.CGenOneReqResultOfdecimal> WriteInterfaceLogAsync(ExchangeService.CGenOneReqInParmOfIntfLogZTgN8_PBM req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService醫事介接/CertificateToDatabase", ReplyAction="http://tempuri.org/IService醫事介接/CertificateToDatabaseResponse")]
        System.Threading.Tasks.Task<ExchangeService.CGenOneReqResultOfint> CertificateToDatabaseAsync(ExchangeService.CCertificateReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService醫事介接/CertificateSpcToDatabase", ReplyAction="http://tempuri.org/IService醫事介接/CertificateSpcToDatabaseResponse")]
        System.Threading.Tasks.Task<ExchangeService.CGenOneReqResultOfint> CertificateSpcToDatabaseAsync(ExchangeService.CCertificateSpcReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService醫事介接/InstitutionToDatabase", ReplyAction="http://tempuri.org/IService醫事介接/InstitutionToDatabaseResponse")]
        System.Threading.Tasks.Task<ExchangeService.CGenOneReqResultOfint> InstitutionToDatabaseAsync(ExchangeService.CInstitutionReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService醫事介接/InstitutionDistToDatabase", ReplyAction="http://tempuri.org/IService醫事介接/InstitutionDistToDatabaseResponse")]
        System.Threading.Tasks.Task<ExchangeService.CGenOneReqResultOfint> InstitutionDistToDatabaseAsync(ExchangeService.CInstitutionDistReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService醫事介接/PersonnelToDatabase", ReplyAction="http://tempuri.org/IService醫事介接/PersonnelToDatabaseResponse")]
        System.Threading.Tasks.Task<ExchangeService.CGenOneReqResultOfint> PersonnelToDatabaseAsync(ExchangeService.CPersonnelReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService醫事介接/PracticeToDatabase", ReplyAction="http://tempuri.org/IService醫事介接/PracticeToDatabaseResponse")]
        System.Threading.Tasks.Task<ExchangeService.CGenOneReqResultOfint> PracticeToDatabaseAsync(ExchangeService.CPracticeReqInParm req);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface IMainServiceChannel : ExchangeService.IMainService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class MainServiceClient : System.ServiceModel.ClientBase<ExchangeService.IMainService>, ExchangeService.IMainService
    {
        
        /// <summary>
        /// 實作此部分方法來設定服務端點。
        /// </summary>
        /// <param name="serviceEndpoint">要設定的端點</param>
        /// <param name="clientCredentials">用戶端認證</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MainServiceClient() : 
                base(MainServiceClient.GetDefaultBinding(), MainServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMainService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MainServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MainServiceClient.GetBindingForEndpoint(endpointConfiguration), MainServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MainServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MainServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MainServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MainServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MainServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ExchangeService.CGenOneReqResultOfIntfPlatformZTgN8_PBM> GetPlatformInfoAsync(ExchangeService.CGenOneStringReqInParm req)
        {
            return base.Channel.GetPlatformInfoAsync(req);
        }
        
        public System.Threading.Tasks.Task<ExchangeService.CGenOneReqResultOfdecimal> WriteInterfaceLogAsync(ExchangeService.CGenOneReqInParmOfIntfLogZTgN8_PBM req)
        {
            return base.Channel.WriteInterfaceLogAsync(req);
        }
        
        public System.Threading.Tasks.Task<ExchangeService.CGenOneReqResultOfint> CertificateToDatabaseAsync(ExchangeService.CCertificateReqInParm req)
        {
            return base.Channel.CertificateToDatabaseAsync(req);
        }
        
        public System.Threading.Tasks.Task<ExchangeService.CGenOneReqResultOfint> CertificateSpcToDatabaseAsync(ExchangeService.CCertificateSpcReqInParm req)
        {
            return base.Channel.CertificateSpcToDatabaseAsync(req);
        }
        
        public System.Threading.Tasks.Task<ExchangeService.CGenOneReqResultOfint> InstitutionToDatabaseAsync(ExchangeService.CInstitutionReqInParm req)
        {
            return base.Channel.InstitutionToDatabaseAsync(req);
        }
        
        public System.Threading.Tasks.Task<ExchangeService.CGenOneReqResultOfint> InstitutionDistToDatabaseAsync(ExchangeService.CInstitutionDistReqInParm req)
        {
            return base.Channel.InstitutionDistToDatabaseAsync(req);
        }
        
        public System.Threading.Tasks.Task<ExchangeService.CGenOneReqResultOfint> PersonnelToDatabaseAsync(ExchangeService.CPersonnelReqInParm req)
        {
            return base.Channel.PersonnelToDatabaseAsync(req);
        }
        
        public System.Threading.Tasks.Task<ExchangeService.CGenOneReqResultOfint> PracticeToDatabaseAsync(ExchangeService.CPracticeReqInParm req)
        {
            return base.Channel.PracticeToDatabaseAsync(req);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMainService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMainService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:53765/DataExchangePlatform.svc");
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MainServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMainService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MainServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMainService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMainService,
        }
    }
}
